package com.bhkim.auth.config.aspect;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.util.Date;

@DynamoDBTable(tableName="KPNP-AUTH-LOG")
@Getter
@ToString
public class DynamoTable {
    @DynamoDBHashKey(attributeName = "Router")
    private String router;

    @DynamoDBHashKey(attributeName = "Sysdate")
    private Long sysdate;

    @DynamoDBAttribute(attributeName = "Payload")
    private String payload;

    private Date lastUpdatedDate;
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getLastUpdatedDate() { return lastUpdatedDate; }
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }


    @Builder
    public DynamoTable(String router, String payload) {
        this.router = router;
        this.sysdate = new Date().getTime();
        this.payload = payload;
    }
}
